### ISSUE TITLE
[FEATURE REQUEST] Nudge keys

### ISSUE THREAD

**Issue by AsaTheUncle** [abrasic/abratools#6]
## Summary
What tool or feature would you like to see added in future versions?

Nudge keys is a method of moving keyframes quickly, with binds or with a button. This request is mostly based on Maya's Animbot implementation of this function.

Functionality:
If there are keyframes on the playhead, move them forward or back a set number of frames.
If no keyframes are selected, bring the closest keyframes to playhead. 

### Usefulness of feature
Having a button to quickly bring keyframes to the playhead is a must for many. For me, that's how I retime my blockouts. Right now in Blender, if I find a frame that I want to move the adjacent key to, I have to stop thinking about my animation, and focus on getting the key in just the right place on the timeline, which can be hard if you have a longer scene and don't want to zoom in the timeline.
Speed is key, and the amount of time we get into the "flow" state, is essential. Not having to fiddle around with UI elements, box-selecting things manually, let's us focus on the timing, spacing and generally the animation alone. 

#### Mockups, prototypes or other useful graphics depicting feature usage (optional)
I recorded a sample how it works in animBot, and a mock up of how it could look like in abraTools

https://github.com/abrasic/abratools/assets/41550157/b2d9f34f-bc9b-4de4-97de-2cdc048fabee

![Photoshop_g6ULMaXyLH](https://github.com/abrasic/abratools/assets/41550157/eb2d395c-ed0d-40fe-a10b-d24943d8a326)

**Comment by abrasic** [comment]
Hello,

Thank you for your feature request, as well as your detailed explanation and examples.
Nudge Key tools have been added into the [latest build](https://github.com/abrasic/abratools/releases/tag/latest). It mimics the behavior to that of animBots. Let me know if you come across any additional issues.

https://github.com/abrasic/abratools/assets/43157991/5e22db47-da28-4384-b4c7-58f60c43adbe

**Comment by AsaTheUncle** [comment]
Thank you so much for adding this feature, it works great!

I'll be closing this issue for now, will reopen if I find issues.
